apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: cf
  name: replicaset-reporter
  namespace: dmaizel-staging-test
spec:
  dependencies:
  - eventName: replicasets
    eventSourceName: replicaset-reporter
    name: replicasets
  eventBusName: codefresh-eventbus
  triggers:
  - retryStrategy:
      duration: 0
      steps: 3
    template:
      conditions: replicasets
      http:
        headers:
          Content-Type: application/json
        method: POST
        payload:
        - dest: data.object
          src:
            dataKey: body
            dependencyName: replicasets
        secureHeaders:
        - name: Authorization
          valueFrom:
            secretKeyRef:
              key: token
              name: codefresh-token
        url: https://app-staging.codefresh.io/2.0/api/events
      name: replicasets
status: {}
